### ISSUE TITLE
Swagger에서 토큰 활용이 되지 않습니다.

### ISSUE THREAD

**Issue by hojoonSong** [pre-onboarding-backend-G/get-your-feeds#19]
## 버그에 대한 설명
![image](https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/51044545/2e41c3fb-a93d-4a3d-903e-057d50e7c8f6)

JwtAuthGuard: canActivate
JwtAuthGuard: handleRequest {
  err: null,
  user: { userId: '653cbf48b9053e96f841c875', email: 'naver@naver.com' },
  info: undefined
}
위 사진처럼 포스트맨에서는 잘 됩니다. 

## 재현 방법
스웨거에서는 헤더에 실리지 않는 문제가 있습니다. Authorize에 토큰값을 수시로 넣었는데도
![image](https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/51044545/21acc33e-d6de-4aa8-986c-9be055f2d637)
개발자 콘솔에서, 헤더가 안실립니다.
main.ts에서는 다음과 같이 변경해주었습니다.

```ts
  const config = new DocumentBuilder()
    .setTitle('Example API')  const config = new DocumentBuilder()
    .setTitle('Example API')
    .setDescription('The Example API description')
    .setVersion('1.0')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        name: 'JWT',
        in: 'query',
      },
      'access-token',
    )
    .build();

    .setDescription('The Example API description')
    .setVersion('1.0')
    .addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        name: 'JWT',
        in: 'query',
      },
      'access-token',
    )
    .build();

```
디버깅값도 여전히 헤더를 달지 못하는 문제가 있는 것 같습니다.
1시간 넘게 매달린 것 같네요

JwtAuthGuard: canActivate
JwtAuthGuard: handleRequest {
  err: null,
  user: false,
  info: Error: No auth token
      at JwtStrategy.authenticate (/home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/passport-jwt/lib/strategy.js:96:26)
      at attempt (/home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/passport/lib/middleware/authenticate.js:369:16)
      at authenticate (/home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/passport/lib/middleware/authenticate.js:370:7)
      at /home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/@nestjs/passport/dist/auth.guard.js:88:3
      at new Promise (<anonymous>)
      at /home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/@nestjs/passport/dist/auth.guard.js:80:83
      at JwtAuthGuard.canActivate (/home/hojun/바탕화면/PROJECT/get-your-feeds/node_modules/@nestjs/passport/dist/auth.guard.js:44:32)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
}

## 예상 동작
스웨거를 해결해야 할 것으로 보임

## 추가 내용
여기에 문제에 대한 다른 내용을 추가합니다.

**Comment by Zamoca42** [comment]
swagger와 관련된 패키지와 설정은 어떤게 있나요? 
미들웨어에 문제가 있으면 필요한 패키지가 더있거나 설정이 더 필요할 수도 있을거같습니다.

```js
.addBearerAuth(
      {
        type: 'http',
        scheme: 'bearer',
        name: 'JWT',
        in: 'query', // -> 'header'
      },
      'access-token',
    )
```
이렇게도 해보셨나요?

**Comment by hojoonSong** [comment]
맨 처음엔 header였는데도 안되더라구요. 다시 한번 확인해보겠습니다!
