### ISSUE TITLE
빌드 시 MongoDB와의 포트충돌

### ISSUE THREAD

**Issue by hojoonSong** [pre-onboarding-backend-G/get-your-feeds#5]
##  이슈 내용
`Error response from daemon: driver failed programming external connectivity on endpoint get-your-feeds-mongodb (b93a042efcd5b361eee8dcb868f2b6960c9f220c16cfdf1730f88d5c457a3e09): Error starting userland proxy: listen tcp4 0.0.0.0:27017: bind: address already in use`

docker compose-up을 하면, 제 리눅스 내부에서 동일한 포트를 쓰고 있어서, 포트에러가 납니다.
다른 프로젝트에서 개발하고 있던 제 MongoDB를 포트문제로 삭제하기가 그래서, 일단 docker-compose에 있는 외부 포트를
ports:
      - '27018:27017' 로 변경해서 쓰고 있긴 합니다.

그냥 저는 개발할때 docker-compose를 .gitignore에 추가해서 개발을 진행해야할까요?

도커 환경으로 개발진행을 하는 것은 처음이여서 문의드립니다! 

##  작업 사항
- [ ] 해당 이슈의 작업사항

<br>

##  관련 이슈
- #이슈 번호

<br>

## 기타사항

<br>

**Comment by Zamoca42** [comment]
> - '27018:27017' 로 변경해서 쓰고 있긴 합니다.

이렇게 바꿨을 때 에러가 발생하지 않나요?
문제가 없다면 커밋할 때 docker-compose.yml의 변경사항에 포함되지 않으면 될거 같습니다.

아니면 docker compose의 mongodb 포트를 논의하고 바꿔보는거도 좋을거 같네요.

**Comment by hojoonSong** [comment]
![image](https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/51044545/911b7d94-6286-4033-b015-d7174796dbb1)

.env.local을 변경해도 포트변경이 되지 않네요? 포트 변경이 가능하면 옮기는 것도 논의 해봤으면 좋겠습니다.

**Comment by Zamoca42** [comment]
> .env.local을 변경해도 포트변경이 되지 않네요?

지금 로컬환경에서 mongodb의 포트를 변경하고 싶으시면 docker compose에서 직접 변경하고 재빌드(`docker compose up --build`) 해줘야합니다. 

그 다음 .env.local에서 docker compose에 맞게 DATABASE_URI나 ME_CONFIG_MONGODB_URL를 변경하면 될거같습니다.

**Comment by hojoonSong** [comment]
아 넵. —build를 다시 해줘야하는 군요! 저 혼자 포트번호를 바꾸고 compose를 건들일 없을테니, 제 gitignore선에서 파일을 추가하고 해결하는 쪽으로 해봐도 되고! 포트변경이 괜찮으면 이야기해봐주셔도 되고 내일 논의해보시죠! 늦은 시간까지 감사합니다 :-)
