### ISSUE TITLE
통계 모듈 스키마 추가

### ISSUE THREAD

**Issue by myeongseoklee** [pre-onboarding-backend-G/get-your-feeds#8]
##  이슈 내용

여러분 불코딩 중이신가요...?

통계 부분 요구사항 분석하다보니, 제가 놓친 부분이 있는 것 같아서 공유드립니다.

통계 기능이 특정 기간 동안의 통계 데이터를 제공하는 것인데요.

처음에는 게시물 스키마에 있는 "createdAt"을 기준으로 데이터 통계를 내면 될거라고 간단하게 생각했는데 요구사항을 곱씹어보니 그게 아닌 것 같아서요.

조회수를 예로 들면,
10월 1일 부터 10월 3일까지의 게시물들의 조회수를
=> "일별" 조회수로 확인하려면 각 게시물의 "일별" 조회수 데이터가 필요합니다.
=> "시간별" 조회수를 확인하려면 각 게시물의 "시간별" 조회수 데이터가 필요합니다.

그렇다면 결국

게시물들의 시간별 통계 데이터가 필요한 것이죠.
기존 article에 있는 통계 데이터는 현재까지 누적데이터일 것이기 때문에 StatisticsSchema가 만들어져야 할 것 같습니다.

여러분의 의견은 어떠신가요?

```suggestion
// StatisticsSchema 예시

type StatisticsSchema {
    content_id: string
    type: string // enum: fb, insta, twitter, thread
    hashtags: ?? // ariticle schema와 동일한 타입으로
    view_count: {count:number, created_at:datetime}[]
    like_count: {count:number, created_at:datetime}[]
    share_count: {count:number, created_at:datetime}[]
    created_at: datetime
}
```

<br>

##  작업 사항
- [ ] 해당 이슈의 작업사항

<br>

##  관련 이슈
- #7 

<br>

## 기타사항

<br>

**Comment by Zamoca42** [comment]
이렇게 된다면 게시물을 조회해서 시간마다 통계 데이터로 넣어주는 방식이 될거같은데 게시물 데이터를 쿼리하는 시간도 조정이 필요하겠네요. 

`view_count: {count:number, created_at:datetime}[]` 이렇게 되면
```js
[
  { count: 1, created_at: 날짜 },
  { count: 5, created_at: 날짜 },
]
```
이렇게 되는걸까요?

**Comment by Zamoca42** [comment]
1. 저렇게 되면 시간대별로 문서객체가 만들어질텐데 유저별로 계속 생성하게되면 데이터가 너무 커지지 않을까요?

**Comment by myeongseoklee** [comment]
> 이렇게 된다면 게시물을 조회해서 시간마다 통계 데이터로 넣어주는 방식이 될거같은데 게시물 데이터를 쿼리하는 시간도 조정이 필요하겠네요.

네. 데이터 타입은 말씀해주신 내용이 맞습니다.

통계 데이터를 외부에서 가져오는 방식은,
cron을 사용하여 일정 시간마다 sns api에 각 게시물의 데이터를 요청하는 서비스로직 작성이 필요할 것 같습니다.
sns의 open api가 하루 전체의 데이터를 시간별로 데이터를 나눠서 보내준다면 하루 단위로 데이터 받아오도록 크론을 짜면 될 것 같고,
하루 단위로만 데이터를 제공한다면 시간별로 각각 데이터를 조회하도록 해서 시간별 데이터를 우리 서비스에서 만들어야 할 것 같습니다.

**Comment by myeongseoklee** [comment]
> 이렇게 된다면 게시물을 조회해서 시간마다 통계 데이터로 넣어주는 방식이 될거같은데 게시물 데이터를 쿼리하는 시간도 조정이 필요하겠네요.
> 
> `view_count: {count:number, created_at:datetime}[]` 이렇게 되면
> 
> ```js
> [
>   { count: 1, created_at: 날짜 },
>   { count: 5, created_at: 날짜 },
> ]
> ```
> 
> 이렇게 되는걸까요?

네. 데이터 타입은 말씀해주신 내용이 맞습니다.

통계 데이터를 외부에서 가져오는 방식은,
cron을 사용하여 일정 시간마다 sns api에 각 게시물의 데이터를 요청하는 서비스로직 작성이 필요할 것 같습니다.
sns의 open api가 하루 전체의 데이터를 시간별로 데이터를 나눠서 보내준다면 하루 단위로 데이터 받아오도록 크론을 짜면 될 것 같고,
하루 단위로만 데이터를 제공한다면 시간별로 각각 데이터를 조회하도록 해서 시간별 데이터를 우리 서비스에서 만들어야 할 것 같습니다.

**Comment by Zamoca42** [comment]
음.. 일정시간마다 외부 sns api를 조회한다는 말씀은, facebook이나 다른 SNS 서비스 api를 조회해서 데이터를 가져온다는 말씀이시죠?
외부 sns을 시간마다 조회하는 것보다 article 모듈에 있는 게시물 목록을 쿼리해서 파싱하는 것은 어떨까요?

게시물 쪽에서 sns 피드를 모아서 통계쪽으로 전달하면 외부 sns으로 여러번 api를 조회하지 않아도 될거 같습니다

**Comment by myeongseoklee** [comment]
> 음.. 일정시간마다 외부 sns api를 조회한다는 말씀은, facebook이나 다른 SNS 서비스 api를 조회해서 데이터를 가져온다는 말씀이시죠? 외부 sns을 시간마다 조회하는 것보다 article 모듈에 있는 게시물 목록을 쿼리해서 파싱하는 것은 어떨까요?
> 
> 게시물 쪽에서 sns 피드를 모아서 통계쪽으로 전달하면 외부 sns으로 여러번 api를 조회하지 않아도 될거 같습니다

움.. 게시물 정보는 유저가 hashtag로 어떤 아티클을 조회했을 때 그 게시물이 db에 없다면 생성되는 데이터이고 그 게시물이 db에 있다면 해당 게시물이 수정된다고 생각했어요.

[인스타그램 open api](https://developers.facebook.com/docs/instagram-api/reference/ig-hashtag/recent-media#reading)를 확인해보니 시간별 조회수 값은 받아올 수 없고, 조회 할 당시의 조회수만 가져올 수 있는 것 같습니다.

이 상황에서 말씀해주신 방식을 적용했을 때의 예를들어 보겠습니다.

> 저는 오늘 회원가입을 했고 10월 20일에 게시한 게시물(저의 계정 태그를 포함한 게시물입니다.)의 조회수를 일별로 보고 싶습니다. 오늘 인스타그램에서 확인해보니 게시물 조회수가 500이었는데 이 조회수가 어떤 속도로 500까지 늘었는지 궁금했거든요. 통계를 조회한 결과, 오늘의 게시물 조회수만 500이라고 떠서 당황했습니다.

유저는 자신의 게시물의 시간별 조회수를 얻으려면 결국, 1시간 마다 스스로 게시물을 조회해야 하는 상황일 것 같습니다. 물론 실제로 그렇게 하기는 힘드니, 시간별 통계를 제공하기 어려운 상황이 되는 것이죠... ㅠ

**Comment by Zamoca42** [comment]
네 그래서 게시물(Article)쪽에서 스케쥴러로 한시간 마다 피드를 조회를 하고 좋아요, 조회수, 새로 등록된 게시물 등이 변화가 있을 때 통계 쪽에서 데이터를 저장해서 시계열로 보여주는게 어떨까요?

**Comment by myeongseoklee** [comment]
> 네 그래서 게시물(Article)쪽에서 스케쥴러로 한시간 마다 피드를 조회를 하고 좋아요, 조회수, 새로 등록된 게시물 등이 변화가 있을 때 통계 쪽에서 데이터를 저장해서 시계열로 보여주는게 어떨까요?

넵 좋은 방법 같습니다. 

그렇다면 cron으로 데이터를 외부 sns에서 가져와서 article에 저장하는 역할을 Article에 두는게 좋을까요? 아니면 Statistics에 두거나 아예 별도로 CronModule을 만드는 것이 좋을까요?

**Comment by Zamoca42** [comment]
<img width="910" alt="스크린샷 2023-10-27 오후 4 32 31" src="https://github.com/pre-onboarding-backend-G/get-your-feeds/assets/96982072/8eee784c-d873-4b7a-8f4f-055ad3c956a1">


> 그렇다면 cron으로 데이터를 외부 sns에서 가져와서 article에 저장하는 역할을 Article에 두는게 좋을까요? 

저도 그게 궁금해서 1차 과제 Notion을 다시 보고 왔는데요. 

외부 SNS api에 직접 조회나 크롤링은 하면 안되니까 자체 생산으로 게시물을 만들어서 해보라고 하신거 같습니다.

그래서 좋아요나 공유같은 API를 만들 때 endpoint로 직접 조회하는 대신 실패하더라도 내부 게시물(Article)에도 좋아요나 공유 수 + 1을 추가하라고 하신거 같네요.

그렇게하면 통계 모듈에서 한시간마다 Article을 조회하는 로직을 만들어서 시간마다 데이터를 저장하는 방법이 있을 수 있겠네요

**Comment by myeongseoklee** [comment]
**issue에 대한 회의 결과, 결론은 다음과 같습니다.**
1. 통계 데이터를 시간별로 저장하는 schema 생성
2. 실제로 1시간 마다 sns api를 호출하여 sns 플랫폼 별로 데이터를 가져올 수 없으니, 가상의 데이터를 mongodb에 넣어서, 구현한 기능이 잘 작동하는지 시연할 수 있도록만 우선 처리하기로 함.
3. 기능 구현이 완성되고 시간이 남는다면, statstics 모듈에 1시간 마다 sns api에 article 데이터 요청하여 받아서 db에 넣는 cron service를 만들면 된다.
> 단, 이때도 시간상 실제 sns api에서 데이터를 받아올 수 없으므로 sns api 콜을 하면 에러가 반환될 것이다. 그 에러를 잡아서(catch) 예외처리를 한다. 예외처리에는 가상의 artcle data를 만들어서 article db에 데이터를 upsert 하는 방식으로 구현하여 실제 서비스가 동작하는 것 처럼 보이게 한다.
